TRUNCATE TABLE "Users" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Parties" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Tasks" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PartyAttendances" RESTART IDENTITY CASCADE;