INSERT INTO "Users"("Username", "Email", "Password", "Avatar")
VALUES
('okej', 'Okeej', 'Okeej', 'Vazi'),
('makisha', 'email', 'makisha', 'avatar'),
('nalog', 'email', 'password', 'avatar'),
('fake', 'email', 'password', 'avatar'),
('vazi', 'email', 'password', 'avatar'),
('lol', 'email', 'password', 'avatar'),
('wow', 'email', 'password', 'avatar'),
('party', 'email', 'password', 'avatar'),
('zurka', 'email', 'password', 'avatar'),
('lego', 'email', 'password', 'avatar'),
('taskEdit', 'email', 'password', 'avatar'),
('pwUpdateTest', 'pwUpdateTest@gmail.com', 'pwUpdateTest123@', 'avatar'),
('pwLoginTest', 'pwLoginTest@gmail.com', 'pwLoginTest123@', 'avatar'),
('pwVisitTest', 'pwVisitTest@gmail.com', 'pwVisitTest123@', 'avatar'),
('pwCreatePartyTest', 'pwCreatePartyTest@gmail.com', 'pwCreatePartyTest123@', 'avatar'),
('pwCancelPartyTest', 'pwCancelPartyTest@gmail.com', 'pwCancelPartyTest123@', 'avatar'),
('pwEditPartyTest', 'pwEditPartyTest@gmail.com', 'pwEditPartyTest123@', 'avatar'),
('pwAttendPartyTest', 'pwAttendPartyTest@gmail.com', 'pwAttendPartyTest123@', 'avatar'),
('pwUnattendPartyTest', 'pwUnattendPartyTest@gmail.com', 'pwUnattendPartyTest123@', 'avatar'),
('pwTaskCreateTest', 'pwTaskCreateTest@gmail.com', 'pwTaskCreateTest123@', 'avatar'),
('pwTaskEditTest', 'pwTaskEditTest@gmail.com', 'pwTaskEditTest123@', 'avatar'),
('pwTaskRemoveTest', 'pwTaskRemoveTest@gmail.com', 'pwTaskRemoveTest123@', 'avatar');